version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  notification-hub:
    lang: golang-middleware
    handler: ./notification-hub
    image: ${REGISTRY:-ttl.sh}/${OWNER:-openfaas-examples}/notification-hub:latest
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.max: "1"
    environment:
      exec_timeout: "1h"
      read_timeout: "1h1s"
      write_timeout: "1h1s"
